#application.yml#  swagger ui页面
#  http://localhost:8081/swagger-ui/index.html#/
#     http://localhost:8081/doc.html#/home



spring:
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sends_home
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 4000ms
      database: 0

mybatis-plus:
  global-config:
    banner: off

logging:
  level:
    root: info

server:
  port: 8082
